/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);

        // IAuthDAO authDAO = new AuthDAO();
        // ICustomerDataDAO customerDAO = new CustomerDataDAO() ;
        // IAccountsDAO accountDAO = new AccountsDAO() ;

        // BankApp bankApp = BankApp.builder().
        // authService(
        //     AuthService.
        //         builder().
        //         authDAO(authDAO).
        //         build()
        // ).accountService(
        //     AccountsService.
        //         builder().
        //         accountDAO(accountDAO).
        //         build()
        // ).customerService(
        //     CustomerService.
        //         builder().
        //         customerDAO(customerDAO).
        //         build()
        // ).build() ;
        
    }
}
